name = "DiscretePopulationGrowth"
uuid = "a1df61a6-dfcd-4d88-b444-fc322c056947"
authors = ["Zenna Tavares <zennatavares@gmail.com>"]
version = "0.1.0"

[deps]
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
